pipeline{
    options {
        buildDiscarder(logRotator(numToKeepStr: '5', artifactNumToKeepStr: '5'))
    }
    agent any

    stages{
        stage('pull from scm'){
            steps{
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], 
                doGenerateSubmoduleConfigurations: false, 
                extensions: [], 
                submoduleCfg: [], 
                userRemoteConfigs: [[url: 'https://github.com/armelsteve/developer.git']]])
            }
        }

        stage('copy files to ec2 instance'){
            steps{
                dir("${WORKSPACE}/jobs/OPS_create_docker_img"){
                    sshagent(['ec2']) {
                             sh """ scp -o StrictHostKeyChecking=no index.html Dockerfile ec2-user@3.88.52.41:/home/ec2-user/dockerfiles """

                        }
            }

            }
        }
        stage('build image'){
            steps{
                dir("${WORKSPACE}/jobs/OPS_create_docker_img"){
                    sshagent(['ec2']) {
                        sh """
                            ssh -o StrictHostKeyChecking=no ec2-user@3.88.52.41 docker build -t app:1.0 /home/ec2-user/dockerfiles/Dockerfile
                            ssh -o StrictHostKeyChecking=no ec2-user@3.88.52.41 docker images
                            ssh -o StrictHostKeyChecking=no ec2-user@3.88.52.41 docker run --name apache -p 5000:80 -d app
                        """
                    }
            }

            }
        }


    }
    post{
        success{
            deleteDir()
        }
        failure{
            deleteDir()
        }
        aborted{
            deleteDir()
        }
        unstable{
            deleteDir()
        }
    }
}